### ISSUE TITLE
wrong debian release url

### ISSUE THREAD

**Issue by pbousek** [robertdebock/ansible-role-zabbix_repository#1]
in variables you are using wrong url to debian 10 and zabbix5.4 (probably same problem is in older releases)

you are trying to get

TASK [ansible-role-zabbix_repository : install (apt)] ****************************************************************************************************************************************
fatal: [some.host.here]: FAILED! => changed=false 
  msg: 'Failure downloading http://repo.zabbix.com/zabbix/5.4/debian/pool/main/z/zabbix-release/zabbix-release_5.4-1+buster_all.deb, HTTP Error 404: Not Found'

but correct url is 

https://repo.zabbix.com/zabbix/5.4/debian/pool/main/z/zabbix-release/zabbix-release_5.4-1%2Bdebian10_all.deb

they are using debian10 instead of release code name "buster (jessie, stretch)"

**Comment by robertdebock** [comment]
Thanks, give me a moment to verify and fix stuff please.

**Comment by pbousek** [comment]
sure, thank you

**Comment by robertdebock** [comment]
With version `5.0.0` this issue should be resolved.

I'll keep an eye on this, since some other repositories depend on this role for me.

Closing once all are verified to work.

**Comment by robertdebock** [comment]
Closing.
